# # finally code block are excuted irespected of thr out come of try ..except ...finally ..else block
# #one of the impotrant use for cases of finally block is in function return values



# def fun():
# try:
#     i=[1,2,3]
#     l=input("enter the number:")
#     print(i[l])
#     return 1
# except:
#     print("some error")
#     return 0
# finally:
#     print("i am executed")
    
#     x = fun()
#     print(x)
    